const ACTOR_LIST_REQUEST = "ACTOR_LIST_REQUEST";
const ACTOR_LIST_SUCCESS = "ACTOR_LIST_SUCCESS";
const ACTOR_LIST_FAILURE = "ACTOR_LIST_FAILURE";

const types = {
	ACTOR_LIST_FAILURE,
	ACTOR_LIST_REQUEST,
	ACTOR_LIST_SUCCESS,
};

export default types;
