const PERSON_LIST_REQUEST = "PERSON_LIST_REQUEST";
const PERSON_LIST_SUCCESS = "PERSON_LIST_SUCCESS";
const PERSON_LIST_FAILURE = "PERSON_LIST_FAILURE";

const PERSON_GET_REQUEST = "PERSON_GET_REQUEST";
const PERSON_GET_SUCCESS = "PERSON_GET_SUCCESS";
const PERSON_GET_FAILURE = "PERSON_GET_FAILURE";

const PERSON_CREATE_REQUEST = "PERSON_CREATE_REQUEST";
const PERSON_CREATE_SUCCESS = "PERSON_CREATE_SUCCESS";
const PERSON_CREATE_FAILURE = "PERSON_CREATE_FAILURE";

const PERSON_EDIT_REQUEST = "PERSON_EDIT_REQUEST";
const PERSON_EDIT_SUCCESS = "PERSON_EDIT_SUCCESS";
const PERSON_EDIT_FAILURE = "PERSON_EDIT_FAILURE";

const PERSON_DELETE_REQUEST = "PERSON_DELETE_REQUEST";
const PERSON_DELETE_SUCCESS = "PERSON_DELETE_SUCCESS";
const PERSON_DELETE_FAILURE = "PERSON_DELETE_FAILURE";

const types = {
	PERSON_LIST_FAILURE,
	PERSON_LIST_REQUEST,
	PERSON_LIST_SUCCESS,
	PERSON_GET_REQUEST,
	PERSON_GET_SUCCESS,
	PERSON_GET_FAILURE,
	PERSON_CREATE_REQUEST,
	PERSON_CREATE_SUCCESS,
	PERSON_CREATE_FAILURE,
	PERSON_EDIT_REQUEST,
	PERSON_EDIT_SUCCESS,
	PERSON_EDIT_FAILURE,
	PERSON_DELETE_REQUEST,
	PERSON_DELETE_SUCCESS,
	PERSON_DELETE_FAILURE,
};

export default types;
