const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
const MOVIE_LIST_FAILURE = "MOVIE_LIST_FAILURE";

const MOVIE_GET_REQUEST = "MOVIE_GET_REQUEST";
const MOVIE_GET_SUCCESS = "MOVIE_GET_SUCCESS";
const MOVIE_GET_FAILURE = "MOVIE_GET_FAILURE";

const MOVIE_CREATE_REQUEST = "MOVIE_CREATE_REQUEST";
const MOVIE_CREATE_SUCCESS = "MOVIE_CREATE_SUCCESS";
const MOVIE_CREATE_FAILURE = "MOVIE_CREATE_FAILURE";

const MOVIE_EDIT_REQUEST = "MOVIE_EDIT_REQUEST";
const MOVIE_EDIT_SUCCESS = "MOVIE_EDIT_SUCCESS";
const MOVIE_EDIT_FAILURE = "MOVIE_EDIT_FAILURE";

const MOVIE_DELETE_REQUEST = "MOVIE_DELETE_REQUEST";
const MOVIE_DELETE_SUCCESS = "MOVIE_DELETE_SUCCESS";
const MOVIE_DELETE_FAILURE = "MOVIE_DELETE_FAILURE";

const MOVIE_GET_ACTORS_REQUEST = "MOVIE_GET_ACTORS_REQUEST";
const MOVIE_GET_ACTORS_SUCCESS = "MOVIE_GET_ACTORS_SUCCESS";
const MOVIE_GET_ACTORS_FAILURE = "MOVIE_GET_ACTORS_FAILURE";

const MOVIE_PATCH_DIRECTOR_REQUEST = "MOVIE_PATCH_DIRECTOR_REQUEST";
const MOVIE_PATCH_DIRECTOR_SUCCESS = "MOVIE_PATCH_DIRECTOR_SUCCESS";
const MOVIE_PATCH_DIRECTOR_FAILURE = "MOVIE_PATCH_DIRECTOR_FAILURE";

const MOVIE_ADD_ACTOR_REQUEST = "MOVIE_ADD_ACTOR_REQUEST";
const MOVIE_ADD_ACTOR_SUCCESS = "MOVIE_ADD_ACTOR_SUCCESS";
const MOVIE_ADD_ACTOR_FAILURE = "MOVIE_ADD_ACTOR_FAILURE";

const types = {
	MOVIE_LIST_FAILURE,
	MOVIE_LIST_REQUEST,
	MOVIE_LIST_SUCCESS,
	MOVIE_GET_REQUEST,
	MOVIE_GET_SUCCESS,
	MOVIE_GET_FAILURE,
	MOVIE_CREATE_REQUEST,
	MOVIE_CREATE_SUCCESS,
	MOVIE_CREATE_FAILURE,
	MOVIE_EDIT_REQUEST,
	MOVIE_EDIT_SUCCESS,
	MOVIE_EDIT_FAILURE,
	MOVIE_DELETE_REQUEST,
	MOVIE_DELETE_SUCCESS,
	MOVIE_DELETE_FAILURE,
	MOVIE_GET_ACTORS_REQUEST,
	MOVIE_GET_ACTORS_SUCCESS,
	MOVIE_GET_ACTORS_FAILURE,
	MOVIE_PATCH_DIRECTOR_REQUEST,
	MOVIE_PATCH_DIRECTOR_SUCCESS,
	MOVIE_PATCH_DIRECTOR_FAILURE,
	MOVIE_ADD_ACTOR_REQUEST,
	MOVIE_ADD_ACTOR_SUCCESS,
	MOVIE_ADD_ACTOR_FAILURE,
};

export default types;
